FROM node:21-alpine AS build-env
WORKDIR /App

COPY . ./
RUN npm ci --prefix Movies.App
RUN npm run build --prefix Movies.App

# Build runtime image
FROM httpd:alpine
WORKDIR /var/www/html
COPY --from=build-env /App/Movies.App/dist .
